### ISSUE TITLE
Does test code fail if prediction is longer than target?

### ISSUE THREAD

**Issue by NoahAmsel** [clay-lab/transductions#18]
Got this bug

```
Traceback (most recent call last):
  File "main.py", line 386, in <module>
    args.func(args)
  File "main.py", line 249, in test_model
    test.test(model, name = args.model, data = iterators)
  File "/Users/noah/Documents/Senior/Clay/Code/transductions/test.py", line 131, in test
    meter.process_batch(logits_narrow, batch.target, model)
  File "/Users/noah/Documents/Senior/Clay/Code/transductions/metrics.py", line 59, in process_batch
    correct = (prediction == target).prod(axis=0)
  File "//miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 28, in wrapped
    return f(*args, **kwargs)
RuntimeError: The size of tensor a (13) must match the size of tensor b (15) at non-singleton dimension 0
```

**Comment by NoahAmsel** [comment]
This is fixed except for the loss meter in evaluate function of training.py. The other meters in test and train work now.

**Comment by NoahAmsel** [comment]
Fixed that last part too^
