### ISSUE TITLE
Allow multiple layers in units

### ISSUE THREAD

**Issue by jopetty** [clay-lab/transductions#32]
Trying to use multiple layers currently fails. For example, the following model
```
[2020-11-23 20:38:37,908][core.trainer][INFO] - TransductionModel(
  (_encoder): SequenceEncoder(
    (_embedding): Embedding(47, 256)
    (_dropout): Dropout(p=0, inplace=False)
    (unit): RNN(256, 256, num_layers=3)
  )
  (_decoder): SequenceDecoder(
    (_embedding): Embedding(47, 256)
    (_dropout): Dropout(p=0, inplace=False)
    (out): Linear(in_features=256, out_features=47, bias=True)
    (unit): RNN(256, 256)
  )
)
```
yields the following error on the first batch:
```
[2020-11-23 20:38:37,909][core.trainer][INFO] - EPOCH 1 / 100
  0%|                                                                                                                          | 0/821 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 15, in main
    trainer.train()
  File "/Users/jacksonpetty/Documents/Development/transductions/core/trainer.py", line 61, in train
    loss = criterion(predictions, target)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 947, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 2215, in nll_loss
    raise ValueError('Expected input batch_size ({}) to match target batch_size ({}).'
ValueError: Expected input batch_size (3) to match target batch_size (5).
```

**Comment by jopetty** [comment]
It looks like multiple layers works in the `encoder` for GRU/GRU and SRN/SRN models, but not in the `decoder`. This probably has to do with assumptions made in the decoding loop about the dimensions of the tensors. For example,
```
[2021-01-04 17:23:59,585][core.trainer][INFO] - TransductionModel(
  (_encoder): SequenceEncoder(
    (_embedding): Embedding(48, 256)
    (_dropout): Dropout(p=0, inplace=False)
    (_unit): RNN(256, 256)
  )
  (_decoder): SequenceDecoder(
    (_embedding): Embedding(48, 256)
    (_dropout): Dropout(p=0, inplace=False)
    (_unit): RNN(256, 256, num_layers=2)
    (_out): Linear(in_features=256, out_features=48, bias=True)
  )
)
```
errors:
```
Traceback (most recent call last):
  File "train.py", line 17, in main
    trainer.train()
  File "/Users/jacksonpetty/Documents/Development/transductions/core/trainer.py", line 77, in train
    output = self._model(batch, tf_ratio=0.5).permute(1, 2, 0)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/jacksonpetty/Documents/Development/transductions/core/models/base_model.py", line 76, in forward
    dec_output = self._decoder(enc_output, tf_ratio=tf_ratio)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/jacksonpetty/Documents/Development/transductions/core/models/sequence_decoder.py", line 132, in forward
    step_result = self.forward_step(dec_step_input)
  File "/Users/jacksonpetty/Documents/Development/transductions/core/models/sequence_decoder.py", line 178, in forward_step
    _, state = self._unit(unit_input, h)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 230, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 201, in check_forward_args
    self.check_hidden_size(hidden, expected_hidden_size)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 195, in check_hidden_size
    raise RuntimeError(msg.format(expected_hidden_size, tuple(hx.size())))
RuntimeError: Expected hidden size (2, 5, 256), got (1, 5, 256)
```

**Comment by jopetty** [comment]
Okay, this works now.
